### PR TITLE
Update Do Not Disturb command

### PR DESCRIPTION
**Pull request by jaklan**
## Description

Set default command to "toggle".

## Type of change

- [ ] New script command
- [ ] Bug fix
- [x] Improvement of an existing script
- [ ] Documentation update
- [ ] Toolkit change
- [ ] Other (Specify)

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by jaklan** [comment]
cc: @exodusanto

**Review by unnamedd — APPROVED** [review]
Looks good to me! ✅ 

Thanks for the update @jaklan!

**Comment by ryan-efendy** [comment]
This is my machine:
image

I did `brew install vitorgalvao/tiny-scripts/calm-notifications` and can confirm I have the program on my machine.
```
~/raycast/script-commands ❯ calm-notifications                                                       Node 17.3.0
Enable, disable, toggle, and show status of Do Not Disturb on macOS Big Sur.

Settings may take a few seconds to visually come into effect.

Usage:
  calm-notifications [-h|--help] <status|on|off|toggle>
```

When I ran it both via the terminal or raycast:
image

It doesn't toggle the DND
image

**Comment by jaklan** [comment]
@ryan-efendy As you already noticed, it's not related to Raycast.
https://github.com/vitorgalvao/tiny-scripts/issues/206

**Pull request merged**
