### PR TITLE
Removing script command that uses a malicious domain. 

### PR DESCRIPTION
**Pull request by tmcarr**
## Description

I removed the script that searched `https://scriptcommands.com` since it appears to be a malicious domain now. 

## Type of change

- [ x ] Other (Script Removal)

## Screenshot

N/A

## Dependencies / Requirements

N/A

## Checklist

- [ x ] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by unnamedd** [comment]
It is not, however, looks like @Pondorasti gave up to keep the website up and running, that's why it seems to be redirected to another place. Before moving on, I prefer to get in touch to him to check if there are any possibility to have the website back up and running, in any other case, I guess we can move on and delete his Script Command.

@Pondorasti would you mind to share you thoughts here?

@dehesa please, don't merge it yet.

**Comment by Pondorasti** [comment]
Thanks for the ping @unnamedd. The website is still up and running at [scriptcommands.alexandru.so](https://scriptcommands.alexandru.so/). I opened https://github.com/raycast/script-commands/pull/909 for fixing the domain and we could probably close this PR in favor of it.

---

Sorry for the trouble. To add some context, I wanted to stop paying the recurring domain price. Some time ago, I set up a redirect from `scriptcommands.com` to `scriptcommands.alexandru.so`, and then I just let the domain expire. If we are still interested in a custom domain, I can accept GH sponsorships and I will use the proceeds towards it.

Note: Interesting to see that someone bought the domain so quickly after it expired. It's most likely due to the high relevancy of the domain, and the scammer saw it as a quick win opportunity.

**Comment by unnamedd** [comment]
@tmcarr this is going to be fixed by #909. 
Do you mind if I close this PR here?

**Comment by tmcarr** [comment]
Go for it! Just wanted to make sure the script functioned properly, or was removed! Thanks everyone!

**Pull request closed without merging**
