### PR TITLE
Local Weather

### PR DESCRIPTION
**Pull request by lukasoppermann**
## Description

This adds inline local weather to quickly check the current temperature.

It can be saved to the favorites to always see what temperature it is.

## Type of change

- [x] New script command

## Screenshot

Screenshot 2022-06-27 at 09 28 09

## Dependencies / Requirements

None

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by crstauf** [comment]
Similar to and possible duplicate of #30.

**Comment by lukasoppermann** [comment]
Well, in a way, but:
1. It's not merged
2. the geo position (at least for me) is quite off. It shows me in Hamburg, I am in Berlin, the weather can be completely different.

**Comment by crstauf** [comment]
> it's not merged

Buhhh, yes, it is: [`current-weather.sh`](https://github.com/raycast/script-commands/blob/master/commands/dashboard/current-weather.sh).

> the geo position is quite off

Yep, wttr.in's identification isn't great. I explicitly set mine to my city using wttr.in's parameters: https://github.com/chubin/wttr.in#usage.

**Comment by lukasoppermann** [comment]
True, somehow, I thought it wasn't. Sorry.

Well, I personally would love to see a better geo location either via this one, or by adjusting yours. Both fine for me. Settings it manually though is a bit annoying if you move around. That's why I tried to get a better geo location out of the box.

**Comment by dehesa** [comment]
Hey @lukasoppermann ,

Thank you for the contribution and taking the time to write here. Your script looks pretty good, but as @crstauf mentioned, there is already a script performing a similar operation and we try to avoid duplicates whenever possible. Your script does however have some nice additions (such as an easy configuration for units and, it seems, better geo location).

Would you mind setting the PR to modify the current script and maybe provide an easy configuration for people who like to set up/hardcode their geo location?

PS: Also a 1m interval refresh rate seems like to often (what about 5 mins)?

**Comment by crstauf** [comment]
Five minutes may also be too often, as wttr.in data source has a limit.

My script command mentions this:

https://github.com/chubin/wttr.in/blob/master/share/static/malformed-response.html

**Comment by lukasoppermann** [comment]
Sure, will do do this. 👍

**Pull request closed without merging**
