### PR TITLE
Use wikipedia.org as default

### PR DESCRIPTION
**Pull request by asantos00**
## Description

Changes wikipedia search script to use wikipedia.org instead of chinese by default (zh)

## Type of change

- [x] Improvement of an existing script

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Review by unnamedd — APPROVED** [review]
Hi @asantos00, 
thanks for your update in your Wikipedia Script Command! 

It's approved!

**Review by PitNikola — CHANGES_REQUESTED** [review]
@asantos00, I was wondering if it would make more sense to introduce a new script command for searching in english wikipedia instead of changing this one. I would assume that it was @Jax0rz's intention to use Chinese version of Wikipedia.

@asantos00, what do you think about renaming this script to "search-in-wikipedia-chinese.sh" and introducing a separate one?

**Comment by unnamedd** [comment]
> @asantos00, I was wondering if it would make more sense to introduce a new script command for searching in english wikipedia instead of changing this one. I would assume that it was @Jax0rz's intention to use Chinese version of Wikipedia.
> 
> @asantos00, what do you think about renaming this script to "search-in-wikipedia-chinese.sh" and introducing a separate one?

@PitNikola I wrote a comment regarding languages in another PR that make sense to bring here, check it out and let me know what you think: https://github.com/raycast/script-commands/pull/230#discussion_r576296377

**Comment by asantos00** [comment]
Would you be fine if I add a "domain" variable to the script (that can be chinese by default)?

I think this would fit @unnamedd suggestion.

The only issue I'm having is about the placeholder, as I think we can't use interpolation in comments. It was 关键词... before and I changed it to Search term...

What do you suggest doing here?

I'm pushing my variable with the domain variable, happy to add more stuff.

**Comment by PitNikola** [comment]
Yeah, I think it's a good middle ground, thanks @asantos00. Let's ship it like this.

@unnamedd, good point about internationalization, we need to think about some guidelines for it. I think this idea with template might be a reasonable solution.

**Pull request merged**
