### PR TITLE
Add Network Quality CLI Command

### PR DESCRIPTION
**Pull request by LanikSJ**
## Description

Network Quality CLI Command for macOS aka Speedtest command.  Slack thread [here](https://raycastcommunity.slack.com/archives/C01AC2X0GMN/p1649876221157519).

## Type of change

- [x] New script command

## Screenshot

Screen Shot 2022-04-14 at 11 05 41 AM

## Dependencies / Requirements

No dependencies required the command exists within macOS.

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by pomdtr** [comment]
Thanks @LanikSJ !

**Comment by astrit** [comment]
Perhaps doing it inline like the speed test script would be better, what do you think ?

And also formatting something like this:
https://github.com/raycast/script-commands/blob/33f3c9b8d6af9e0f391c56bcaac0921ce27e2d2f/commands/dashboard/speedtest.sh#L40

**Comment by LanikSJ** [comment]
> Perhaps doing it inline like the speed test script would be better, what do you think ?

I don't think I'm skilled enough to know how to do that. 🙂

**Comment by dehesa** [comment]
Thanks for the contribution @LanikSJ and @pomdtr . It looks great.

**Pull request merged**
