### PR TITLE
Domain to IP

### PR DESCRIPTION
**Pull request by pernielsentikaer**
## Description

Lookup the IP address of any given domain

## Screenshot

3uu0amajoq0

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by unnamedd** [comment]
Hey @pernielsentikaer, very interesting first contribution!

**Review by unnamedd — APPROVED** [review]

**Comment by pernielsentikaer** [comment]
Seems to be doing the same as #20 which also copies the IP (got confused by the name) - I think this script should be removed again, or maybe incorporate so the other script in #20 would have a way to not copy to clipboard, I'm not sure if thats possible yet?

**Comment by PitNikola** [comment]
I would double check with @crstauf if he's up for those IP scripts updated to input mode. Though I can imagine that in some cases using clipboard might be a better flow for some people. I'm fine if we have both in this repository.
If we end up adding this one, let's move it also to `ip` sub-directory.

**Review by thomaspaulmann — CHANGES_REQUESTED** [review]
Command looks good. Let's move it to the `ip` subfolder and then it should be good to go into master. Great first contribution 👏

**Comment by crstauf** [comment]
This is a duplicate of two commands already in the repo: [get-url-ip-v4.sh](https://github.com/raycast/script-commands/blob/master/commands/developer-utils/ip/get-url-ip-v4.sh) and [get-url-ip-v6.sh](https://github.com/raycast/script-commands/blob/master/commands/developer-utils/ip/get-url-ip-v6.sh), unless I'm missing something...?

**Comment by thomaspaulmann** [comment]
Oh good catch! I was under the impression that it still uses the clipboard as input instead of arguments. Gonna close this then because it's a duplicate.

**Pull request closed without merging**
