### PR TITLE
Add Script Commands: Spotify Now Playing Song URL to Clipboard

### PR DESCRIPTION
**Pull request by jacc**
(Per @unnamedd's suggestions, I re-opened the PR from #52 with the correct icon as a draft once #51 is merged.)

This script copies the now playing song on Spotify as a URL.

### CODE REVIEW

**Comment by unnamedd** [comment]
@jacc, the pull request #51 was merged!

**Comment by thomaspaulmann** [comment]
@jacc this is a great addition! Just recently shared a song with a friend of mine and would have loved to use your command. Since #51 is merged, feel free to open a PR and get this command in to share it with other music enthusiasts :-)

**Comment by jacc** [comment]
Just moved it to ready to review! You should be able to PR it, glad to hear that my script will be useful 😄

**Review by thomaspaulmann — CHANGES_REQUESTED** [review]
I forgot to mention that we did a restructuring and moved all commands into a subdirectory. Your command should be placed into `commands/media/spotify` next to all other Spotify related commands. The logo is already in place.

Could you please rebase your branch and move the script? Thanks and sorry that I forgot to mention this before, my bad!

**Comment by jacc** [comment]
...I attempted to rebase my branch and push the changes but I think I broke something in the process as there is now 82 commits 😅 let me know if I should just reopen the PR.

**Comment by thomaspaulmann** [comment]
Yeah something is really weird :D Let's create a new PR with a clean state that cherry-picks your important commits. Please close this PR after you have opened the new one. Thanks for keeping our history clean. Super appreciated!

**Pull request closed without merging**
