### PR TITLE
Create messenger

### PR DESCRIPTION
**Pull request by Tony0410**
## Type of change

- [x] New script command
- [ ] Bug fix
- [ ] Improvement of an existing script
- [ ] Documentation update
- [ ] Toolkit change
- [ ] Other (Specify)

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by Tony0410** [comment]
usings cript

**Comment by Tony0410** [comment]
new script

**Review by Tony0410 — COMMENTED** [review]
new script

**Review by Tony0410 — COMMENTED** [review]
done

**Review by Tony0410 — COMMENTED** [review]
ok

**Review by unnamedd — CHANGES_REQUESTED** [review]
Hey @jaklan, 👋
Long time no see, don't you think?

I have made some comments. Please take a look and request a review for a second round. 😉

**Pull request closed without merging**
