### PR TITLE
Speaker Setup.py

### PR DESCRIPTION
**Pull request by kyellareddy**
## Description

This is a script that tests speaker setups by playing a simple sound through the left audio channel and then the right audio channel.

- [x] New script command

## Screenshot

https://github.com/raycast/script-commands/assets/68571978/cb3f131b-9740-48bf-9de2-927b43641c02

## Dependencies / Requirements

1. There are two files in the Speaker Setup folder titled Left.mp3 and Right.mp3
They are both required for the script to work.
2. Install the playsound Python package from https://pypi.org/project/playsound/

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by kyellareddy** [comment]
That looks good.

**Comment by kyellareddy** [comment]
Should I copy/paste that bash code into a new push request?

**Comment by dehesa** [comment]
Yes, please.

**Comment by kyellareddy** [comment]
Ok. I added a new commit here with a new file called 'Speaker Setup.sh'

**Pull request merged**
