### PR TITLE
feat: adding show-notifications command

### PR DESCRIPTION
**Pull request by iloveitaly**
## Description

Applescript to expand notifications on macOS

## Type of change

- [x] New script command

## Screenshot

Run the script, notifications are expanded

## Dependencies / Requirements

None, `osascript` is bundled with macOS

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Review by unnamedd — APPROVED** [review]
It looks good to me, however, as I am using British English, it doesn't work for me or to anyone else who isn't using American English in the System, perhaps you want to write something to warn the user about that.

**Comment by iloveitaly** [comment]
How does it not work? What word is problematic?

**Comment by unnamedd** [comment]
> How does it not work? What word is problematic?

I use my system in the British English, which means that the word "_Center_" (US), for me, and other users, will be "_Centre_" (UK). As this is the case of your Script Command, worth to mention such problem in body of the file, because I am quite sure someone may download it and it will not work, but the user won't understand why. 

At least explaining that, it won't solve, but will explain.

Let me show you how the system identify it for me.
image

image

**Comment by grzegorzkrukowski** [comment]
hey @iloveitaly for me even in US English the script is not working. It doesn't detect "Notification Center" window until I expand it manually - only then the script picks up the window and executes the `click of the group` which is probably not the desired behavior.

Maybe we can find a better way to find a window than using the localized name? 
Can the Notification Center process have more windows? If not maybe we can always pick the first one? 

As @unnamedd mentioned - would be great to add error handling in case the window cannot be found and we cannot find a reliable way to make it work for all languages.

**Comment by dehesa** [comment]
Hey @iloveitaly,

This is another PR where you don't react on feedback (like #685 or #841). We do appreciate the contributions, but it is annoying to keep the PRs open for such a long time.

I will be closing this one for now.

**Comment by iloveitaly** [comment]
@dehesa understand it's annoying, but being ok with longer feedback cycles when a free open-source contribution is being offered is a good approach to encouraging more contributions.

Is the stance here that if a script does not support all locales it shouldn't be accepted? In this case I can't test the UK wording easily and someone could easily mutate this script to adjust the wording.

**Pull request closed without merging**
