### PR TITLE
Fix network-quality script

### PR DESCRIPTION
**Pull request by crstauf**
## Description

Fix issue described in #795.

## Type of change

- [x] Bug fix
 
## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by crstauf** [comment]
@dehesa What is necessary to get this fix merged?

**Review by joaopcm — APPROVED** [review]
Congrats! This is not only a PR, it's an art! ⭐ 

---

external-content duckduckgo com

> “I once saw him kill three men in a bar... With a pencil.”

**Comment by dehesa** [comment]
Hi @crstauf, apologies for the long delay. I tried to run your script and I am getting this. Any ideas?
Network Quality

**Comment by crstauf** [comment]
@dehesa Will you please try `tolower` (instead of `toLower`) and see if that works for you?

**Comment by dehesa** [comment]
Yes, lowercase works.

**Comment by dehesa** [comment]
Great, thanks!

**Pull request merged**
