### PR TITLE
Auto check scripts and set executable

### PR DESCRIPTION
**Pull request by crstauf**
@unnamedd @thomaspaulmann 

## Description

GitHub Action to check and set permissions of all files (except documentation and images) in `commands` directory to be executable.

## Type of change

- [x] Toolkit change

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by unnamedd** [comment]
Hi @crstauf,

thanks for the script and the workflow. This is planned to be done directly by Toolkit, but I didn’t work on it due to unavailable time from my side. 

As you already implemented it and looks good to me, you have my approval. 

As soon we have the implementation being done by Toolkit, this shell script should be deprecated. Sounds good?

**Review by unnamedd — APPROVED** [review]

**Comment by thomaspaulmann** [comment]
Amazing! I was already wondering if you have some local script to check for non-executable scripts :-)

**Comment by crstauf** [comment]
> Amazing! I was already wondering if you have some local script to check for non-executable scripts :-) 

@thomaspaulmann Indeed I do, actually as a Script Command; submitted in #50 but was rejected.

**Comment by thomaspaulmann** [comment]
Yeah this makes more sense to have it as automation instead of a script command. Let the machines do the "heavy" work :-P

**Comment by crstauf** [comment]
@thomaspaulmann Automate All The Things; in development, though, there's no automation at that point. That's where the script comes in handy.

**Pull request merged**
