### PR TITLE
NotePlan3 commands

### PR DESCRIPTION
**Pull request by gdamberg**
## Type of change

Script commands to work with [NotePlan3](https://noteplan.co) 

- [ x] New script command

## Screenshot
screenshot

## Dependencies / Requirements

Bash, python3 and pbpaste (all of which come preinstalled)

## Checklist

- [ x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Review by fe9lix — CHANGES_REQUESTED** [review]
Thanks for the submission! A small change request: Could you supply a 64px icon? (and our standard format is .png)

**Comment by fe9lix** [comment]
Another question I have is: Could most of this be solved with our built-in feature "Quicklinks"? (https://raycast.com/extensions/quicklinks/)

**Comment by gdamberg** [comment]
Yes, You are right about 'QuickLinks'. I got carried away after creating the first command ;-)

Removing.

**Comment by gdamberg** [comment]
new screenshot:
screenshot

**Comment by dehesa** [comment]
Thanks for the PR, @gdamberg

**Pull request merged**
