### PR TITLE
Fix: make screenshot command executable

### PR DESCRIPTION
**Pull request by crstauf**
Ran `chmod +x system/screensaver.sh`.

### CODE REVIEW

**Comment by unnamedd** [comment]
I’m not sure if this change will have any effect on my machine, I guess in any case, I will have to set it as executable using chmod. What do you think?

**Comment by crstauf** [comment]
@unnamedd I think all script commands in the git repo should be executable. There was talk about automating it I think somewhere in Slack.

**Comment by unnamedd** [comment]
I completely agree with you, but I guess Raycast will be able to run it without have to set it as executable, I’m not sure now, I’m  not on computer, but tomorrow we can double check it if you want.

**Comment by crstauf** [comment]
I was unable to find the command in Raycast prior to `chmod` adjustment.

**Comment by unnamedd** [comment]
Huum... Weird... but, anyway, if worked for you, great! :D

**Comment by crstauf** [comment]
I don't understand... will this be merged?

**Comment by unnamedd** [comment]
Probably yes, but I don’t have permission to do this, only the Raycast developers. Sorry 😔

**Comment by thomaspaulmann** [comment]
It would be great to automate this with a linter or bot that makes sure nothing non-executable is getting committed.

**Comment by thomaspaulmann** [comment]
Thanks for fixing this @crstauf. Did you check if there are any other non-executable commands?

**Comment by crstauf** [comment]
> Did you check if there are any other non-executable commands?

@thomaspaulmann I did not; I tried to use the screensaver command and discovered it wasn't indexed. Perhaps a Raycast Script Command to check for any Raycast Script Commands that are not executable? ;)

**Comment by thomaspaulmann** [comment]
Haha inception :D

**Comment by unnamedd** [comment]
> It would be great to automate this with a linter or bot that makes sure nothing non-executable is getting committed.

I will check that!

**Comment by thomaspaulmann** [comment]
Yes, the `FileManager` exposes a [method](https://developer.apple.com/documentation/foundation/filemanager/1414159-isexecutablefile) to check if a file is executable.

**Comment by unnamedd** [comment]
Good to know @thomaspaulmann. For the Toolkit I'm using TSC (Tool Supporting Core) to read the files, as it is written on top of FileManager, I'm sure they added support for this kind of check there!

**Pull request merged**
