### PR TITLE
Added script to create a new Google Meet meeting and copy the url 

### PR DESCRIPTION
**Pull request by MujibAzizi**
## Description

This script adds support for quickly creating a new Google Meet session. It also copies the URL. 

**Note**: Right now, it only supports Google Chrome. I'm planning to add support for other browsers too.

## Type of change

- [x] New script command

## Dependencies / Requirements

Google Chrome (I'm planning to add more browsers!)

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by unnamedd** [comment]
Hi @MujibAzizi, are you still working in this PR? It's in draft and for that reason no one reviewed it yet.
Do you need any help?

**Comment by MujibAzizi** [comment]
Hi @unnamedd. I'd like to add support for more browsers first before requiring a review as it does not seem very appropriate to only allow support for Google Chrome.

I have not had the time to look into detecting the default browser without the use of an external dependency. 

If you'd like to help — feel free to contribute to my repo as well.

**Comment by unnamedd** [comment]
Hi @MujibAzizi,
do you have any intention to work on this pull request?

**Comment by MujibAzizi** [comment]
> Hi @MujibAzizi,
> 
> do you have any intention to work on this pull request? 

Yes! I will put in some effort this weekend. 

Thank you for the check-in :)

**Comment by MujibAzizi** [comment]
@unnamedd I made some progress which I did not push yet. I will be doing so soon.

**Comment by MujibAzizi** [comment]
@unnamedd I have added support for Safari. 

I also attempted to add support for Firefox. However, Firefox does not provide support for AppleScript. The only reliable way possible seemed to bring Firefox to the front and perform a copy-paste (CMD+L, CMD+C). I found this to be too intrusive and decided against adding it.

**Review by fe9lix — CHANGES_REQUESTED** [review]
Hi! Could you uppercase the title ("Create Google Meet Meeting") or maybe just use "Open Google Meet"?

**Comment by MujibAzizi** [comment]
@fe9lix Sure thing! `Open Google Meet` seems like the best choice. 

I've pushed my changes.

**Review by fe9lix — APPROVED** [review]

**Pull request merged**
