### PR TITLE
feat(media): spotify icon added

### PR DESCRIPTION
**Pull request by japanese-goblinn**

### CODE REVIEW

**Comment by crstauf** [comment]
Hmmm, Spotify icon isn't showing for me. May need to be re-committed.

**Comment by japanese-goblinn** [comment]
> Hmmm, Spotify icon isn't showing for me. May need to be re-committed.

🤔

**Comment by japanese-goblinn** [comment]
> Hmmm, Spotify icon isn't showing for me. May need to be re-committed.

did you try to `reload scripts`?

**Comment by crstauf** [comment]
@japanese-goblinn Sorry, I mean it's not showing in the PR:

https://github.com/raycast/script-commands/blob/8230154c9da4e4784f87284c0dbf1d3053f823fb/media/images/spotify-logo.png

**Comment by japanese-goblinn** [comment]
Screen Shot 2020-11-10 at 20 59 02

I'm confused  why it not showing on `GitHub` 😢

**Comment by crstauf** [comment]
Showing now. 👍

**Comment by japanese-goblinn** [comment]
@crstauf is it showing now?

**Comment by japanese-goblinn** [comment]
well, as I see it's showing up

**Review by unnamedd — APPROVED** [review]

**Pull request merged**
