### PR TITLE
Add WIFI Password script command

### PR DESCRIPTION
**Pull request by astrit**
## Description

A very simple script to copy the WIFI Password from your current session. 
Inspired by @rauchg

## Type of change

- [x] New script command
- [ ] Bug fix
- [ ] Improvement of an existing script
- [ ] Documentation update
- [ ] Toolkit change
- [ ] Other (Specify)

## Screenshot
Screen-Recording-2021-10-26-at-11 09 41

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by astrit** [comment]
@unnamedd please let me know if this is good

**Review by unnamedd — APPROVED** [review]
Hi @astrit, thanks a lot for your changes! 

It looks good to me now and we are good to go! ✅

**Comment by astrit** [comment]
@unnamedd thanks for confirmation. 
Perhaps will get a response from @imthath-m soon as well.

**Comment by unnamedd** [comment]
Yeap, you will!

**Pull request merged**
