### PR TITLE
Add Script Command: current-weather

### PR DESCRIPTION
**Pull request by crstauf**

### CODE REVIEW

**Review by unnamedd — APPROVED** [review]
Great addition @crstauf! 😍

**Comment by thomaspaulmann** [comment]
Ha, you beat me on this command! Looks like `https://wttr.in/?format="%c+%f+%w+in+%l` spits out a rather long string. Should we cap it somehow with an regex?

**Comment by crstauf** [comment]
@thomaspaulmann It fits for me. I suspect that the `+in+%l` is the problem, as that's the location, and that could be very long for some and very short for others. I decided to include the location in case the geolocation was wrong, so the user had the opportunity to confirm.

**Comment by crstauf** [comment]
@thomaspaulmann Limited the location output to everything before the first comma in fad4c71.

**Comment by thomaspaulmann** [comment]
Nice! This makes it more streamlined with our UI. Gonna get that straight into my favorites :-)

**Pull request merged**
