### PR TITLE
Add Script Commands: Google Lighthouse and PageSpeed Insights

### PR DESCRIPTION
**Pull request by crstauf**

### CODE REVIEW

**Comment by PitNikola** [comment]
@crstauf, could you please move these commands into dedicated google subdirectory? Also could you please provide a screenshot of these commands? (to ensure that they look good in the list)

**Review by PitNikola — CHANGES_REQUESTED** [review]
Left comment above

**Comment by crstauf** [comment]
Screenshot:

Screen Shot 2020-11-13 at 1 16 30 PM

**Review by PitNikola — APPROVED** [review]
👍

**Pull request merged**
