### PR TITLE
Emojis

### PR DESCRIPTION
**Pull request by lucasrcosta**
## Description

Scripts generated to copy emojis to the clipboard in the Github/Slack format (`:emoji:`)

PS: I think this should be an native extension, I find it so much easier than Character Viewer. If you make it so, just drop me a line. 😉 

## Type of change

- [X] New script command
- [ ] Bug fix
- [ ] Improvement of an existing script
- [ ] Documentation update
- [ ] Toolkit change
- [ ] Other (Specify)

## Screenshot

image

## Dependencies / Requirements

https://www.npmjs.com/package/clipboardy

## Checklist

- [X] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by mattisssa** [comment]
Hey @lucasrcosta! Thanks for the PR, actually it seems quite overkill and will have huge performance implications. We’re planning to add a native emoji picker soon, so stay tuned 🙃

**Comment by mattisssa** [comment]
My Safari crashes when I'm trying to review the PR 😁
I think @unnamedd had the same issue during the night

**Comment by unnamedd** [comment]
For sure I had @mattisssa haha!

**Comment by lucasrcosta** [comment]
No problem @mattisssa, just leave it as a statement of what's possible. But if you want to try it I could make it work by adding one directory at a time, it really make life easier.

**Comment by dextermb** [comment]
Perhaps a single emoji command with an argument would work better than 1.7K files?

**Comment by lucasrcosta** [comment]
@dextermb there's already a solution of that kind. My point here is an experience analog to Github or Slack. Like this 😄 . I don't mind having the PR closed. It works for me and I made my point. 😉

**Comment by lucasrcosta** [comment]
Someone even made a whole app for this feature https://matthewpalmer.net/rocket/

**Comment by unnamedd** [comment]
@lucasrcosta I use Rocket for a couple of years and it is very nice! I recommend!

**Comment by lucasrcosta** [comment]
@unnamedd too skeptical to use something that records my keys 😬 . I'd prefer to use Raycast whenever I need...

**Comment by unnamedd** [comment]
then you may know that Apple restrict any attempt of softwares to record what being input in a secure text field, right? In this case, Rocket won’t steal much from you ;)

**Comment by lucasrcosta** [comment]
> Hey @lucasrcosta! Thanks for the PR, actually it seems quite overkill and will have huge performance implications. We’re planning to add a native emoji picker soon, so stay tuned 🙃

Hey @mattisssa, any news on that emoji picker? Do you plan to keep the colon format like Github and Slack?

**Comment by lucasrcosta** [comment]
Happy to see this feature went live.
https://twitter.com/raycastapp/status/1496508301483429893

**Comment by mattisssa** [comment]
Haha, yes, it has been almost a year since then. Sorry, I didn't see your question before for some reason.. 🙈 
@lucasrcosta

**Pull request closed without merging**
