### PR TITLE
Add a Mullvad package

### PR DESCRIPTION
**Pull request by PSalant726**
## Description

A package of script commands wrapping the [Mullvad CLI](https://mullvad.net/en/help/cli-command-wg/), to control the local connection to a Mullvad VPN tunnel.

## Type of change

- [x] New [package of] script command[s]
- [x] Documentation update

## Screenshot

See [the included README.md file](https://github.com/raycast/script-commands/blob/1831245ebf4380ba9af4313ac3bf27302705b28f/commands/apps/mullvad/README.md).

## Dependencies / Requirements

1. The Mullvad CLI: https://mullvad.net/en/help/cli-command-wg/
2. The `fzf` utility (search only): https://github.com/junegunn/fzf

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by unnamedd** [comment]
Hey @PSalant726, this PR is still a draft. Do you have plans to work on it?

**Comment by PSalant726** [comment]
@unnamedd Yes, I haven't forgotten about this. I believe the scripts are each in a usable state, but I still plan to make a few tweaks and add some documentation.

**Comment by unnamedd** [comment]
Great! Thanks Phil.

**Comment by fe9lix** [comment]
Hi! Is this functional and can be merged? (Hard to test for me...)

**Comment by PSalant726** [comment]
@fe9lix _"It works on my machine"_ :trollface: 

Seriously, I believe this is in a working state. Perhaps we could recruit other Mullvad users in the Slack community to do some further testing?

**Comment by fe9lix** [comment]
I trust it works on your machine 😉. I'd suggest we merge it, and you can ask some people if they want to give it a try. If they run into issues, you can always add fixes later.

**Pull request merged**
