### PR TITLE
Add a script command for searching in App Store app

### PR DESCRIPTION
**Pull request by andreiborisov**
## Description

Add a script command for searching in App Store app.

## Type of change

- [x] New script command

## Screenshot

CleanShot 2021-01-31 at 01 34 11@2x
CleanShot 2021-01-30 at 23 55 16@2x

## Dependencies / Requirements

No dependencies required.

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by andreiborisov** [comment]
I wasn't sure in what section to put it

**Comment by thomaspaulmann** [comment]
I think web searches are fine for now. Thanks for your first contribution @andreiborisov 🎉

**Comment by unnamedd** [comment]
@thomaspaulmann actually, even if currently the good folder to place this script commands would be `web searches`, it doesn’t fit well there. I’d say that the perfect fit is the folder `apps/`, especially because it’s using the Mac App Store’s URL Scheme. What do you think?

**Comment by thomaspaulmann** [comment]
I get your point and I don't have strong feelings about it. I think it fits in both folders. Feel free to move the script and the icon if you feel strongly about it. In the hint side, we maybe should have named the folder `web-searches` just `search` to have a general category.

**Comment by unnamedd** [comment]
> I get your point and I don't have strong feelings about it. I think it fits in both folders. Feel free to move the script and the icon if you feel strongly about it. In the hint side, we maybe should have named the folder `web-searches` just `search` to have a general category.

I agree with the rename from `web-searches` to `searches`, it will fit more cases than today!

**Pull request merged**
