### PR TITLE
Add Bitwarden Send support

### PR DESCRIPTION
**Pull request by PSalant726**
## Type of change

- [x] New script command[s]
- [x] Documentation update

## Screenshot

See the updated [README.md file](https://github.com/raycast/script-commands/blob/cd966068f409d81f2dc8c823970f526922ee7524/commands/password-managers/bitwarden/README.md).

## Dependencies / Requirements

No new dependencies.

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by PSalant726** [comment]
I'm not sure where the changes to `commands/README.md` and `commands/extensions.json` came from?

**Comment by unnamedd** [comment]
> I'm not sure where the changes to `commands/README.md` and `commands/extensions.json` came from?

There’s a GitHub Action which runs a job every time we have a new commit in the master of this repo, the job compile the Toolkit, runs a command to read all the script commands in the commands folder and then generate the readme and the extensions.json.

ping me on slack if you want to know more about it Phil.

**Comment by fe9lix** [comment]
Hi! Any updates on this, i.e. is the draft status set intentionally, or can we merge? CC @unnamedd

**Comment by PSalant726** [comment]
@fe9lix This is intentionally a draft PR. There are more tweaks and features coming that belong in the same PR as the current changes. I haven't had much time lately to continue work, but I expect to continue contributing within the next week or two.

**Comment by fe9lix** [comment]
Alright, then we'll keep it open for now and bother you again in one or two weeks latest... 😉

**Comment by PSalant726** [comment]
@unnamedd I was able to get rid of the diff in the unrelated files by pulling my upstream with the `-X theirs` option.

@fe9lix This is now ready for review! 🎉 🎉

**Review by fe9lix — APPROVED** [review]

**Pull request merged**
