### PR TITLE
Feat(Conversions/Space-fixer): add Space-fixer script

### PR DESCRIPTION
**Pull request by RealTong**
## Type of change

- [x] New script command
- [ ] Bug fix
- [ ] Improvement of an existing script
- [ ] Documentation update
- [ ] Toolkit change
- [ ] Other (Specify)

## Screenshot
Raycast 2024-03-21 at 12 11 57

## Dependencies / Requirements
This script requires the package `pangu`. Install it with `pip install pangu` or `pnpm install pangu` or `npm install pangu`.

npm: https://www.npmjs.com/package/pangu
pypi: https://pypi.org/project/pangu/

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Review by grzegorzkrukowski — CHANGES_REQUESTED** [review]
Hey @RealTong - thanks for your contribution.

The script is looking good, but there is one small detail we should fix: the `pangu_path`.
Right now you hardcoded the path, including your own username - which will make it fail on other machines.

You also give 3 options to install pangu: pip, pnpm, npm - and your path assumes it's always `pnpm` - even if we change it to `~/Library/pnpm/pangu` - it will fail for all other installation and will require others to update the path here.

First of all - I would recommend using `which` to find the right path for `pangu` on other machines.
`pangu_path=$(which pangu)`

Secondly, to support all different types of installation, you may want to adapt the $PATH for each of them, to make it work on as many configurations as we can by default.

Something like this should work:
```
# pip, pnp paths
export PATH="$HOME/.pyenv/shims:$HOME/Library/pnpm:$PATH"
# nvm paths
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
# npm paths
NPM_BIN_PATH=$(which npm)
if [[ -n "$NPM_BIN_PATH" ]]; then
    NPM_DIR=$(dirname "$NPM_BIN_PATH")
    export PATH="$NPM_DIR:$PATH"
fi

pangu_path=$(which pangu)
# REST OF THE SCRIPT
```

**Comment by RealTong** [comment]
> Hey @RealTong - thanks for your contribution.
> 
> The script is looking good, but there is one small detail we should fix: the `pangu_path`. Right now you hardcoded the path, including your own username - which will make it fail on other machines.
> 
> You also give 3 options to install pangu: pip, pnpm, npm - and your path assumes it's always `pnpm` - even if we change it to `~/Library/pnpm/pangu` - it will fail for all other installation and will require others to update the path here.
> 
> First of all - I would recommend using `which` to find the right path for `pangu` on other machines. `pangu_path=$(which pangu)`
> 
> Secondly, to support all different types of installation, you may want to adapt the $PATH for each of them, to make it work on as many configurations as we can by default.
> 
> Something like this should work:
> 
> ```
> # pip, pnp paths
> export PATH="$HOME/.pyenv/shims:$HOME/Library/pnpm:$PATH"
> # nvm paths
> export NVM_DIR="$HOME/.nvm"
> [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
> # npm paths
> NPM_BIN_PATH=$(which npm)
> if [[ -n "$NPM_BIN_PATH" ]]; then
>     NPM_DIR=$(dirname "$NPM_BIN_PATH")
>     export PATH="$NPM_DIR:$PATH"
> fi
> 
> pangu_path=$(which pangu)
> # REST OF THE SCRIPT
> ```

I'm grateful for your insight on this issue. Your proposed solution worked perfectly. Thanks for your help!

**Comment by grzegorzkrukowski** [comment]
Great - thanks for updating the script. We will merge it now

**Review by grzegorzkrukowski — APPROVED** [review]
it all looks good now after the update path

**Pull request merged**
