### PR TITLE
Add Various Script Commands

### PR DESCRIPTION
**Pull request by mrmartineau**
## Description

This PR adds a few web searches relating to npm and front-end development:

- njt (npm jump to) search
- caniuse.com search
- bundlephobia.com search
- npms.io search
- open npm package repo using ghub.io
- search giphy.com
- link unfurl test (unfurler.com)
- search Wayback Machine

## Type of change

- [x] New script command
- [ ] Bug fix
- [ ] Improvement of an existing script
- [ ] Documentation update
- [ ] Toolkit change
- [ ] Other (Specify)

### njt
image

### caniuse.com
image

### bundlephobia
image

### npms
image

### ghub.io (repo)
image

### giphy
image

### unfurl
image

### Wayback Machine
image

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by fe9lix** [comment]
Hey @mrmartineau, thanks for the contribution (giphy, yey! ;)). Some comments:

- The njt.sh script doesn't work, probably because of missing quotes at the end of the open call
- Titles should be capitalized to be consistent with how Raycast commands are named, i.e. change to: Open NPM Package Repo, Bundlephobia Cost, Unfurl, etc..
- Package name should be something shorter, like a category (the design doesn't really support a longer description here at the moment)
- Caniuse: I guess this still classifies as web search, so let's move it there as well

**Review by fe9lix — CHANGES_REQUESTED** [review]
Hey @mrmartineau, thanks for the contribution (giphy, yey! ;)). Some comments:

- The njt.sh script doesn't work, probably because of missing quotes at the end of the open call
- Titles should be capitalized to be consistent with how Raycast commands are named, i.e. change to: Open NPM Package Repo, Bundlephobia Cost, Unfurl, etc..
- Package name should be something shorter, like a category (the design doesn't really support a longer description here at the moment)
- Caniuse: I guess this still classifies as web search, so let's move it there as well

**Comment by mrmartineau** [comment]
@fe9lix apologies for the bug, it must've been a copy/paste bug because my forked repo is not the same location as where my raycast commands are stored.

I have updated some of the other commands inline with your comments, however some services like npm do not need to be capitalised because its name is specifically lowercased.

**Comment by fe9lix** [comment]
Sure, fix names such as npm can stay. Can you update the package name to _Web Searches_ in all cases so that we're consistent with the rest of the web searches here?

**Comment by mrmartineau** [comment]
@fe9lix I have updated the `packageName` values now. I'm all for consistency, but I feel that using a more descriptive value for that field is helpful to users, but at the end of the day, they can easily change it themselves of course...

**Review by fe9lix — APPROVED** [review]

**Pull request merged**
