### PR TITLE
Add command to sample a colour from the screen

### PR DESCRIPTION
**Pull request by jesse-c**
## Description

Use the new `NSColorSampler` to sample a colour from anywhere on the screen.

## Type of change

- [x] New script command

## Screenshot

CleanShot 2020-12-17 at 23 45 50

## Dependencies / Requirements

n/a

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Review by fe9lix — CHANGES_REQUESTED** [review]
Great contribution! One ask I'd ask you to do is adding a check for macOS 10.14 (Mojave) and print an error message if needed. `NSColorSampler` is only available from macOS 10.15+ on. You can check the contribution guidelines for some examples and best practices.

**Comment by fe9lix** [comment]
Update: For Swift specifically, we don't mention an example here. So what you can do is using `if #available(OSX 10.15, *) {` ...

**Comment by itsnwa** [comment]
Amazing, thank you for the great contribution @jesse-c! This will replace Sip app for me 🤩

**Comment by jesse-c** [comment]
@fe9lix that's a good point! I've added a check. Thank you for the hint on how to do it too.

@itsnwa exactly! This is to replace Sip for me too. Obviously this command is very simple so far, but it can be improved upon. :)

**Review by fe9lix — APPROVED** [review]

**Comment by jesse-c** [comment]
Thank you! :)

**Pull request merged**
