### PR TITLE
Add a template to execute a binary

### PR DESCRIPTION
**Pull request by pomdtr**
## Description

Add a binary template script.

## Type of change

- [x] Other (Specify)

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by pomdtr** [comment]
Unfortunately it does not work :'(

```
Reason: Process tried to run, but failed
Domain: scripts
Time: 10:06:34.649
Underlying: 
	Domain: NSPOSIXErrorDomain 8
	Reason: Exec format error
```

**Comment by pomdtr** [comment]
I think the best to achieve this is just:

```
#!/bin/bash

// Raycast Script Command Template
// Duplicate this file and remove ".template." from the filename to get started.
// See full documentation here: https://github.com/raycast/script-commands
//
// Required parameters:
// @raycast.schemaVersion 1
// @raycast.title My First Script
// @raycast.mode fullOutput
// @raycast.packageName Raycast Scripts
//
// Optional parameters:
// @raycast.icon 🤖
// @raycast.currentDirectoryPath ~
// @raycast.needsConfirmation false
//
// Documentation:
// @raycast.description Write a nice and descriptive summary about your script command here
// @raycast.author Your name
// @raycast.authorURL An URL for one of your social medias

exec path/to/binary "$@"
```

**Comment by dehesa** [comment]
Hey @pomdtr,

Thanks for the contribution. I have two thought with this, though:
1. Currently the templates folder just have a single file for each supported language.
2. We do have templates files within `commands` subfolders when needed.

This files feels a bit out of place and I don't think it adds that much value there. What do you think?

**Comment by pomdtr** [comment]
I think you are right. At first the pr was dedicated to a golang command (see [c06554c](https://github.com/raycast/script-commands/pull/774/commits/c06554cadf08978558ac917386ebe2b14e92b187)), but I realized that it did not work with raycast.

I then thought about the wrapping strategy, but the pr might not make sense anymore.

**Pull request closed without merging**
