### PR TITLE
Use new folder icons

### PR DESCRIPTION
**Pull request by es183923**
## Description

Use the new folder icons instead of the emoji for `open-home.sh`, `open-desktop.sh`, `open-downloads.sh`, `open-documents.sh`, and `open-library.sh`.

## Type of change

- [x] Improvement of an existing script

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Review by unnamedd — APPROVED** [review]
Great update @es183923, thanks a lot for the PR!

**Comment by fe9lix** [comment]
Hi @es183923 – could you resize the icons to 64x64px?

**Review by fe9lix — CHANGES_REQUESTED** [review]
Hi @es183923 – could you resize the icons to 64x64px? (We've just updated our recommended icon size...)

**Comment by es183923** [comment]
Okay, I updated the images.

**Comment by es183923** [comment]
oops accidentally added an extra commit
ill close this and reopen one

**Pull request closed without merging**
