### PR TITLE
Add Script Command: is-up

### PR DESCRIPTION
**Pull request by crstauf**

### CODE REVIEW

**Review by PitNikola — CHANGES_REQUESTED** [review]
As in previous PRs let's add a comment section explicitly stating the dependency and installation instruction.

**Comment by crstauf** [comment]
@PitNikola Moved into subdirectory and added dependency comments.

**Review by thomaspaulmann — CHANGES_REQUESTED** [review]
Looks like this is just a network request against `https://isitup.org/` with the hostname, e.g. `https://isitup.org/github.com.json`. Lets make this script simpler and just use `cURL`.

**Comment by crstauf** [comment]
> Looks like this is just a network request

@thomaspaulmann [Took a look](https://github.com/sindresorhus/is-up/blob/master/index.js), and this is more than "just a network request", and is outside my expertise to build in Bash, namely the following:

1. correct the URL to be properly formatted (ex: remove the protocol)
2. parse the JSON without a dependency (removing dependencies is your whole point)

If you want to give it a go, please do so; otherwise, let me know and I'll close this PR.

**Comment by fe9lix** [comment]
Hi @crstauf! I'd propose to close this PR, mostly due to introducing a bunch of NPM dependencies. Skimming the "is-up" package, it seems like all there's really happening to check a domain such as raycast.com is a `curl "https://isitup.org/raycast.com.json"`. Feel free to open a new PR that uses built-ins such as curl.

**Comment by crstauf** [comment]
@fe9lix Please see my [prior comment](https://github.com/raycast/script-commands/pull/66#issuecomment-731888362).

**Pull request closed without merging**
