### PR TITLE
Switch external display sources

### PR DESCRIPTION
**Pull request by goodhyun**
## Description

Switch external display between DisplayPort and HDMI without touching the monitor hardware via ddc control. 

## Type of change

- [x] New script command
- [ ] Bug fix
- [ ] Improvement of an existing script
- [ ] Documentation update
- [ ] Toolkit change
- [ ] Other (Specify)

## Screenshot

It just switches to the other machine that is connected to that input source/port. 

## Dependencies / Requirements

You'll need a proper DDC command line tools.
Arm64(M1) :  https://github.com/waydabber/m1ddc
x86(Intel):  https://github.com/kfix/ddcctl

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by dehesa** [comment]
Hi @goodhyun,

Thank you for your contribution. Could you make the following changes?
- Add the dependency documented lines as described [here](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md#scripts-that-require-installation-of-runtimes-and-dependencies).
- Add a `# @raycast.description`  to the `# Optional parameters` section with a phrase explaining what each command does.
- Add  `# @raycast.packageName External Display` to the `# Optional parameters` section.
- Change the `# @raycast.title` to show what the command does. I recommend `Switch to DP` and `Switch to HDMI`. That title will be displayed to the left of the package name, which is `External Display`.

**Review by dehesa — CHANGES_REQUESTED** [review]
Hi @goodhyun,

Thank you for your contribution. Could you make the following changes?
- Add the dependency documented lines as described [here](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md#scripts-that-require-installation-of-runtimes-and-dependencies).
- Add a `# @raycast.description`  to the `# Optional parameters` section with a phrase explaining what each command does.
- Add  `# @raycast.packageName External Display` to the `# Optional parameters` section.
- Change the `# @raycast.title` to show what the command does. I recommend `Switch to DP` and `Switch to HDMI`. That title will be displayed to the left of the package name, which is `External Display`.

**Comment by goodhyun** [comment]
@dehesa thanks for the review. Just pushed more commits to meet your requirements.

**Review by dehesa — APPROVED** [review]
Great stuff! Thank you @goodhyun!

**Pull request merged**
