### PR TITLE
Enhance IP address commands to use inline mode

### PR DESCRIPTION
**Pull request by crstauf**
Because of the _Copy Output_ action (`CMD+.`) enhance the IP address commands to use `inline` mode.

### CODE REVIEW

**Comment by unnamedd** [comment]
I didn't understand the reason why the `pbcopy` was removed from the scripts, one of the great benefit of those scripts was exactly the copy of the IP v4/v6 to the clipboard. The `inline`+`refreshTime` is great, but in those specific cases, I'd rather copy of the information instead of the visualization.

**Comment by crstauf** [comment]
> I didn't understand the reason why the `pbcopy` was removed from the scripts

@unnamedd The _Copy Output_ action makes the `pbcopy` unnecessary.

> the great benefit of those scripts was exactly the copy of the IP v4/v6 to the clipboard

The _Copy Output_ action copies the output to the clipboard. Changing the command `inline` gives all the current functionality, with the added benefit of a quick glance to check the IP address rather than pasting somewhere.

**Comment by unnamedd** [comment]
I download two of the modified scripts here ([this](developer-utils/get-external-ip-v4.sh) and [this](https://github.com/raycast/script-commands/blob/211bd5068696775f5beb04b1fbdb11d7144e7b68/developer-utils/get-local-ip-v4.sh) and I didn't achieve the expected result. Did I miss something?

**Comment by crstauf** [comment]
@unnamedd These steps should work:

1. Open Raycast
2. Select Local IPv4 inline Script Command
3. Press `ENTER` to refresh your IP address
4. Press `CMD + .` to copy the command's output
5. Paste clipboard somewhere to confirm

Here's a video of me executing the above steps: https://cloudup.com/c3CTZ8kMTw4.

**Comment by unnamedd** [comment]
Indeed @crstauf, make sense. I forgot completely about the `Copy Output` shortcut! 

I agree with you the use of `pbcopy` is not needed, but I'm afraid others might forget the `Copy Output` as well, like me.
Make sense to wait for more opinions.

**Comment by shpakovski** [comment]
🤯

**Pull request merged**
