### PR TITLE
Create column-to-comma.sh

### PR DESCRIPTION
**Pull request by jdmcd**
Adds a script that uses the column data from your clipboard and converts it to comma separated. For example:

```
1
2
3
```

Becomes:

`1,2,3`

### CODE REVIEW

**Comment by jdmcd** [comment]
@thomaspaulmann I just realized I created the file at the root level - let me update that

**Comment by thomaspaulmann** [comment]
Great one!

How about creating a directory named `conversions` (or alternatively `format`) and add it there? Doesn't really fit the `system` one.

**Comment by jdmcd** [comment]
No problem, updated!

**Comment by thomaspaulmann** [comment]
Perfect and thanks for the quick update. Let's get it merged 🎉

**Pull request merged**
