### PR TITLE
Agenda commands

### PR DESCRIPTION
**Pull request by mtellis2**
## Description

Script commands to use with [Agenda application](https://agenda.com/) (A great note app to track standups).

## Type of change

- [x] New script command

## Screenshot

screenshot

## Dependencies / Requirements

Nothing other than the Agenda application.

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by es183923** [comment]
LGTM!

**Comment by dehesa** [comment]
Hi @mtellis2,

Thank you for the contribution. Did you try one of our latest built-in features: [Quicklinks](https://raycast.com/extensions/quicklinks)? Could most of this be solved with Quicklinks?

**Comment by daniel-joseph** [comment]
@dehesa it really depends actually. Script commands allow you to have optional inputs, whereas Quicklinks don't. So say for example I made a script command to create a new note with an optional date and optional text. You can't replicate that with Quicklinks and it will throw an error. Does that make sense? Quicklinks are quicker to setup, but don't have optional inputs. All inputs are required in the form of queries.

**Comment by nhojb** [comment]
Thanks @daniel-joseph - perhaps we need to consider optional parameters for Quicklinks.

**Pull request merged**
