### PR TITLE
Record simulator script added

### PR DESCRIPTION
**Pull request by maximkrouk**

### CODE REVIEW

**Comment by shpakovski** [comment]
Perfect, thanks!

**Comment by maximkrouk** [comment]
This script probably needs more description.
- Errors are not very descriptive even in the `fullOutput` mode
- You should cancel process to stop recording

**Comment by shpakovski** [comment]
Right, it would be nice to improve these bits 🙏

**Comment by maximkrouk** [comment]
Sure I'll make a new PR when I find out how to make the script better 🙂

**Comment by unnamedd** [comment]
@maximkrouk it is not documented yet, but you can use three new metatags when you push your new pull request making this script better.

```
# @raycast.author Your Name
# @raycast.authorURL Your Social Network Account
# @raycast.description A small description of your script command
```

**Pull request merged**
