### PR TITLE
Moved media scripts in separate directories

### PR DESCRIPTION
**Pull request by japanese-goblinn**
For me this solves problem that I'm not using `Apple Music` and don't want it in Raycast suggestions, so I can only add `media/spotify` and that's all. If you want both - just add two folders.

### CODE REVIEW

**Comment by unnamedd** [comment]
Today, Raycast or the [Toolkit](https://github.com/raycast/script-commands/tree/master/Tools/Toolkit) doesn't reads the content of subdirectories, whether to add the scripts on the Script Commands Preferences in Raycast nor in the documentation files ([json](https://github.com/raycast/script-commands/blob/master/extensions.json) and [markdown](https://github.com/raycast/script-commands/blob/master/extensions.md)). 

That being said, I'd like to ask: why not disable the script commands you're not using? 
Giving me as an example: I don't use Spotify and then, all those script commands are disabled.

**Comment by crstauf** [comment]
I submitted a proposal that would support resolving this: #47.

**Comment by japanese-goblinn** [comment]
> That being said, I'd like to ask: why not disable the script commands you're not using?

because I don't what do disable every unused script manually

> Giving me as an example: I don't use Spotify and then, all those script commands are disabled.

If you want to use only Apple Music just add `media/apple-music`, if you want Spotify - just add `media/spotify`, if you want both - just add both 😅. I think its better to add a subdirectory that contains scripts related to music service than deactivate manually every script that I'm not using.

Screen Shot 2020-11-10 at 20 15 00

**Comment by crstauf** [comment]
This was discussed previously in https://github.com/raycast/script-commands/pull/33#issuecomment-723565321, and determined that the use of `packageName` is preferable.

Please see https://github.com/raycast/script-commands/pull/49#issuecomment-724840882.

**Comment by japanese-goblinn** [comment]
> That being said, I'd like to ask: why not disable the script commands you're not using?

because I don't what do disable every apple script

> Giving me as an example: I don't use Spotify and then, all those script commands are disabled.

I don't understand. If you want to use only Apple Music just add `media/apple-music`, if you want Spotify - just add `media/spotify`, if you want both - just add both 😅. I think its better to add a subdirectory that contains scripts related to music service than deactivate manually every commit that I'm not using.

Screen Shot 2020-11-10 at 20 15 00


> This was discussed previously in [#33 (comment)](https://github.com/raycast/script-commands/pull/33#issuecomment-723565321), and determined that the use of `packageName` is preferable.
> 
> Please see [#49 (comment)](https://github.com/raycast/script-commands/pull/49#issuecomment-724840882).

Sorry, I didn't see. No questions now.

**Comment by unnamedd** [comment]
> If you want to use only Apple Music just add `media/apple-music`, if you want Spotify - just add `media/spotify`, if you want both - just add both 😅. I think its better to add a subdirectory that contains scripts related to music service than deactivate manually every script that I'm not using.

I continue to disagree with you that we need to have subdirectories, but you have a point, and what maybe @thomaspaulmann , @PitNikola and @shpakovski can discuss it there, about an implementation of sub categories like we have in the [documentation](https://github.com/raycast/script-commands/blob/master/extensions.md) based on the `packageName` and making them possible to enable/disable the whole subcategory.

In my opinion, this should be enough without the need to create subdirectories creating more complexity to everyone.

**Comment by japanese-goblinn** [comment]
> > If you want to use only Apple Music just add `media/apple-music`, if you want Spotify - just add `media/spotify`, if you want both - just add both 😅. I think its better to add a subdirectory that contains scripts related to music service than deactivate manually every script that I'm not using.
> 
> I continue to disagree with you that we need to have subdirectories, but you have a point, and what maybe @thomaspaulmann , @PitNikola and @shpakovski can discuss it there, about an implementation of sub categories like we have in the [documentation](https://github.com/raycast/script-commands/blob/master/extensions.md) based on the `packageName` and making them possible to enable/disable the whole subcategory.
> 
> In my opinion, this should be enough without the need to create subdirectories creating more complexity to everyone.

Yep, absolutely agree.

**Comment by maximkrouk** [comment]
Hi there. +1 for packages I already gave a little feedback [here](https://github.com/raycast/script-commands/issues/47#issuecomment-724859199), but also +1 for manually adding subdirectories as script directories, instead of disabling scripts from shared directories, it's much more inconvenient.

**Pull request closed without merging**
