### PR TITLE
Add weather checker

### PR DESCRIPTION
**Pull request by jaklan**
## Description

Add weather checker using https://wttr.in

## Type of change

- [x] New script command
- [ ] Bug fix
- [ ] Improvement of an existing script
- [ ] Documentation update
- [ ] Toolkit change
- [ ] Other (Specify)

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by crstauf** [comment]
Possible duplicate of `dashboard/current-weather.sh`.

**Comment by jaklan** [comment]
@crstauf no, it isn't. `dashboard/current-weather.sh` doesn't allow to specify the location, works in `inline` mode and shows only, well, current weather, not 3-day detailed forecast.

**Comment by mattisssa** [comment]
Looks nice! Thanks for contributing 👍

**Comment by crstauf** [comment]
@jaklan Thus the use of the word "possible". Didn't give it a thorough looking over, was just noting.

**Pull request merged**
