### PR TITLE
Set or move packageName meta on all script commands

### PR DESCRIPTION
**Pull request by crstauf**
Pending outcome of conversation of #47, setting `packageName` meta of all Script Commands would be necessary.

### CODE REVIEW

**Comment by thomaspaulmann** [comment]
@crstauf do you plan to finish this PR? Now that we have aligned the structure of the repository and that it's wise to have the `packageName` always defined, you can go ahead with this change. Please double check that you cover all cases. Thanks for keeping our repo in a clean and consistent state.

**Comment by crstauf** [comment]
@thomaspaulmann Yes I do, thank you for following up. I was waiting for a definitive decision on this, as well as for things to settle in, and I believe now is appropriate. Will complete this PR this week.

**Comment by fe9lix** [comment]
Hey guys, any updates here?

**Comment by crstauf** [comment]
> any updates here?

@fe9lix I was hoping my open PRs would be approved and merged before updating this; is that possible?

**Comment by fe9lix** [comment]
@crstauf We don't have any other outstanding PRs now, so when you update this one once more, we can merge it as well.

**Comment by crstauf** [comment]
@fe9lix Updated.

**Review by fe9lix — APPROVED** [review]

**Comment by fe9lix** [comment]
Cheers!

**Pull request merged**
