### PR TITLE
add lowfi command

### PR DESCRIPTION
**Pull request by nohzafk**
## Description

Script command for start [lowfi](https://github.com/talwat/lowfi) command in a wezterm window, run the second time to bring the lowfi window to the front

## Type of change

- [x] New script command

## Screenshot

Untitled

## Dependencies / Requirements

Require
- [lowfi](https://github.com/talwat/lowfi)
- [WezTerm](https://wezfurlong.org/wezterm/index.html)

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by giedreblekaite** [comment]
Thank you for your PR! Unfortunately, the script command is not working for me. I get this: 
Screenshot 2024-12-03 at 16 59 15

**Comment by nohzafk** [comment]
> Thank you for your PR! Unfortunately, the script command is not working for me. I get this: 
> 
> Screenshot 2024-12-03 at 16 59 15
> 
> 

did you install [lowfi](https://github.com/talwat/lowfi) ?

If you did, can you verify it's installed in one of the directories in your PATH, or add its location to your PATH

**Comment by giedreblekaite** [comment]
> > Thank you for your PR! Unfortunately, the script command is not working for me. I get this:
> > Screenshot 2024-12-03 at 16 59 15
> 
> did you install [lowfi](https://github.com/talwat/lowfi) ?
> 
> If you did, can you verify it's installed in one of the directories in your PATH, or add its location to your PATH

No, I didn't have it. Please update the comments that lowfi needs to be installed as well because currently they tell about wezterm only. By the way, I noticed that the script always starts a new lowfi instance even when wezterm window is visible. Maybe this could be fixed as well?

**Comment by nohzafk** [comment]
Thx for your feedback 😄 I've updated the instructions of how to install lowfi.

Could you install lowfi and then test it to see if the script can invoke the wezterm window if run the second time?

It's a little bitt tricky to get this effect work, I've spent quite some time on it.

Which macOS version are you using? I've tested it on the latest 15.1.1

**Comment by giedreblekaite** [comment]
> Thx for your feedback 😄 I've updated the instructions of how to install lowfi.
> 
> Could you install lowfi and then test it to see if the script can invoke the wezterm window if run the second time?
> 
> It's a little bitt tricky to get this effect work, I've spent quite some time on it.
> 
> Which macOS version are you using? I've tested it on the latest 15.1.1

Thanks for updated instructions. I've been using your script several times already on 15.1.1 but it always opens a new window instead of activating the current one. Could it be due to the fact that I have tabs set up like that? Maybe your window setup is different in any way.
Screenshot 2024-12-09 at 10 58 21

**Comment by nohzafk** [comment]
can you show your wezterm window that runs lowfi? 

the apple script is trying to find a wezterm window whose title contains "lowfi" and then bring it to to the upfront and focus on it.

**Comment by giedreblekaite** [comment]
> can you show your wezterm window that runs lowfi?
> 
> the apple script is trying to find a wezterm window whose title contains "lowfi" and then bring it to to the upfront and focus on it.

Here's my screencast: 

https://github.com/user-attachments/assets/33837949-cf9d-46bc-8299-6c1ea17eb482

**Comment by nohzafk** [comment]
Thanks for you feedback and patience. I fix the issue, wezterm should run in the background when lowfi process starts. 

The script worked previously if there is a wezterm window opened already, I tested both scenarios (no wezterm window exists, already a wezterm window exists ) and it works now.

**Comment by giedreblekaite** [comment]
> Thanks for you feedback and patience. I fix the issue, wezterm should run in the background when lowfi process starts.
> 
> The script worked previously if there is a wezterm window opened already, I tested both scenarios (no wezterm window exists, already a wezterm window exists ) and it works now.

Works great now, doesn't start a new instance if one is already playing. Good stuff! Thank you very much!

**Review by giedreblekaite — APPROVED** [review]

**Pull request merged**
