### PR TITLE
Add scripts to change casing

### PR DESCRIPTION
**Pull request by robertcoopercode**
## Description

Adds 6 scripts to change the casing of text:

- uppercase
- lowercase
- kebab case
- camel case
- title case
- snake case

Essentially just a port of https://github.com/gillibrand/alfred-change-case

## Type of change

- [x] New script command

## Screenshot

CleanShot 2021-03-20 at 19 56 55

## Dependencies / Requirements

Requires python, but should be installed by default on Mac OS

## Checklist

- [x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Review by fe9lix — CHANGES_REQUESTED** [review]
Thanks for your contribution! Could you update the packageName to sth. that better reflects the category, e.g. "Conversions"? (see other conversion scripts...)

**Comment by robertcoopercode** [comment]
> Thanks for your contribution! Could you update the packageName to sth. that better reflects the category, e.g. "Conversions"? (see other conversion scripts...)

Can you explain what `sth` means?

**Comment by fe9lix** [comment]
Sorry: sth. = something

**Comment by fe9lix** [comment]
Regarding the shared code: Would you mind keeping all required code in each of the individual scripts? The reason is that we'd like to keep the scripts self-contained as much as possible (easier sharing). Some duplication is okay.

**Comment by robertcoopercode** [comment]
Updated

**Comment by robertcoopercode** [comment]
I just noticed there is aa script that covers uppercase and lowercase and title case: https://github.com/raycast/script-commands/blob/master/commands/developer-utils/transform-case.sh

The title case result is not as elegant, but the uppercase and lowercase look to work well and are in bash.

**Review by fe9lix — APPROVED** [review]

**Pull request merged**
